from typing import Protocol
from uuid import UUID
from src.application.domain.quiz import Quiz


class QuizRepository(Protocol):
    async def add_one(self, quiz: Quiz) -> UUID: ...

    async def get_all(self) -> list[Quiz]: ...

    async def update_one(self, quiz_id, new_quiz: Quiz) -> UUID: ...

    async def delete_one(self, quiz_id) -> UUID: ...

#     async def get_by_id(self, quiz_id): ...

#     async def get_by_user_id(self, user_id: int): ...
