from typing import Any, Protocol


class AdminRepository(Protocol):
    model: Any

    async def add_one(self, domain_object): ...

    async def get_all(self): ...

    async def update_one(self, key, updated_domain_object): ...

    async def delete_one(self, object_id): ...
